title: Joheen Chakraborty
position: Physics PhD Candidate
affiliation: Massachusetts Institute of Technology
email: joheen (at) mit.edu
keywords: minimal academic
github_link: https://github.com/joheenc
twitter: https://twitter.com/joheenc
ads: https://ui.adsabs.harvard.edu/public-libraries/ok8XrfneQjOLDGnOZQI_IA
avatar: ./assets/avatar.png
favicon: ./assets/favicon.png
favicon_dark: ./assets/favicon.png
google_analytics: UA-111540567-4

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - minimal-light.gemspec
