title: Joheen Chakraborty
position: Ph.D. Student in Physics
affiliation: Massachusetts Institute of Technology
email: joheen (at) mit.edu
keywords: minimal academic
github_link: https://github.com/joheenc
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
