title: Joheen Chakraborty
position: Ph.D. Student in Physics
affiliation: MIT
email: joheen (at) mit.edu
keywords: minimal academic
github_link: https://github.com/joheenc
twitter: https://twitter.com/joheenc
ads: https://ui.adsabs.harvard.edu/public-libraries/ok8XrfneQjOLDGnOZQI_IA
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - minimal-light.gemspec
